// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odevatasayar.Helpers;

namespace odevatasayar.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("odevatasayar.Models.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("OrganizasyonId");

                    b.HasKey("Id");

                    b.HasIndex("OrganizasyonId");

                    b.ToTable("Bolge");
                });

            modelBuilder.Entity("odevatasayar.Models.BolgeLider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolgeId");

                    b.Property<int>("KullaniciId");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("BolgeLider");
                });

            modelBuilder.Entity("odevatasayar.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Email");

                    b.Property<string>("Gsm");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("odevatasayar.Models.Ofis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolgeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.ToTable("Ofis");
                });

            modelBuilder.Entity("odevatasayar.Models.OfisLider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KullaniciId");

                    b.Property<int>("OfisId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OfisId");

                    b.ToTable("OfisLider");
                });

            modelBuilder.Entity("odevatasayar.Models.Organizasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SirketId");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("Organizasyon");
                });

            modelBuilder.Entity("odevatasayar.Models.OrganizasyonLider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KullaniciId");

                    b.Property<int>("OrganizasyonId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OrganizasyonId");

                    b.ToTable("OrganizasyonLider");
                });

            modelBuilder.Entity("odevatasayar.Models.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sirket");
                });

            modelBuilder.Entity("odevatasayar.Models.SirketLider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KullaniciId");

                    b.Property<int>("SirketId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SirketId");

                    b.ToTable("SirketLider");
                });

            modelBuilder.Entity("odevatasayar.Models.Takim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("OfisId");

                    b.HasKey("Id");

                    b.HasIndex("OfisId");

                    b.ToTable("Takim");
                });

            modelBuilder.Entity("odevatasayar.Models.TakimLider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KullaniciId");

                    b.Property<int>("TakimId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TakimId");

                    b.ToTable("TakimLider");
                });

            modelBuilder.Entity("odevatasayar.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KullaniciId");

                    b.Property<string>("Name");

                    b.Property<int>("TakimId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TakimId");

                    b.ToTable("Uye");
                });

            modelBuilder.Entity("odevatasayar.Models.Bolge", b =>
                {
                    b.HasOne("odevatasayar.Models.Organizasyon", "Organizasyon")
                        .WithMany()
                        .HasForeignKey("OrganizasyonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.BolgeLider", b =>
                {
                    b.HasOne("odevatasayar.Models.Bolge", "Bolge")
                        .WithMany()
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.Ofis", b =>
                {
                    b.HasOne("odevatasayar.Models.Bolge", "Bolge")
                        .WithMany()
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.OfisLider", b =>
                {
                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.Organizasyon", b =>
                {
                    b.HasOne("odevatasayar.Models.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.OrganizasyonLider", b =>
                {
                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Organizasyon", "Organizasyon")
                        .WithMany()
                        .HasForeignKey("OrganizasyonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.SirketLider", b =>
                {
                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.Takim", b =>
                {
                    b.HasOne("odevatasayar.Models.Ofis", "Ofis")
                        .WithMany()
                        .HasForeignKey("OfisId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.TakimLider", b =>
                {
                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("odevatasayar.Models.Uye", b =>
                {
                    b.HasOne("odevatasayar.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("odevatasayar.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
